// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inventory.Domain.Entities;

public partial class Stock
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public Guid WarehouseId { get; set; }

    public int Quantity { get; set; }

    public int ReservedQty { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}