// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Catalog.Infrastructure.Models;

public partial class Product
{
    public Guid Id { get; set; }

    public string Sku { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public Guid? CategoryId { get; set; }

    public decimal Price { get; set; }

    public string Currency { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductSpec> ProductSpecs { get; set; } = new List<ProductSpec>();
}