// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Catalog.Infrastructure.Models;

public partial class ProductSpec
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Product Product { get; set; }
}