// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Report.Application.Abstractions.Persistence;
using Report.Application.Features.Dtos;
using ReportService.Domain.Entities;
using System;
using System.Collections.Generic;

namespace ReportService.Infrastructure.Persistence;

public partial class ReportDbContext : DbContext, IReportDbContext
{
    public ReportDbContext(DbContextOptions<ReportDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ReportOrder> ReportOrders { get; set; }

    public virtual DbSet<ReportProductStat> ReportProductStats { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ReportOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportOr__3214EC07867FD525");

            entity.ToTable("ReportOrders", "report");

            entity.HasIndex(e => e.CreatedAt, "IX_ReportOrders_CreatedAt");

            entity.HasIndex(e => e.Status, "IX_ReportOrders_Status");

            entity.HasIndex(e => e.UserId, "IX_ReportOrders_UserId");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ReportOrders_CreatedAt");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.Total).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<ReportProductStat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ReportPr__3214EC07B975ABEE");

            entity.ToTable("ReportProductStats", "report");

            entity.HasIndex(e => new { e.ProductId, e.Month }, "UX_ReportProductStats_Product_Month").IsUnique();

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TotalRevenue).HasColumnType("decimal(18, 2)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}