// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Payment.Domain.Entities;

public partial class PaymentEvent
{
    public Guid Id { get; set; }

    public Guid PaymentId { get; set; }

    public string EventType { get; set; }

    public string Data { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Payment Payment { get; set; }
}