// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportService.Domain.Entities;

public partial class ReportOrder
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public decimal Total { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }
}