// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ordering.Domain.Entities;

public partial class OutboxMessage
{
    public Guid Id { get; set; }

    public string EventType { get; set; }

    public string Payload { get; set; }

    public DateTime OccurredAtUtc { get; set; }

    public DateTime? ProcessedAtUtc { get; set; }

    public string Error { get; set; }
}