// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReportService.Domain.Entities;

public partial class ReportProductStat
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string ProductName { get; set; }

    public int QuantitySold { get; set; }

    public decimal TotalRevenue { get; set; }

    public DateOnly Month { get; set; }
}