// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryService.Domain.Entities;

public partial class StockMovement
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public Guid WarehouseId { get; set; }

    public int ChangeQty { get; set; }

    public string Reason { get; set; }

    public string RefType { get; set; }

    public Guid? RefId { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}