FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ../../Ecommerce.sln .
COPY ../../src/Orchestrator ./Orchestrator

WORKDIR /src/Orchestrator/Orchestrator.Worker
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Orchestrator.Worker.dll"]
